### PR TITLE
feat: add scala & java syntax highlighting

### PR DESCRIPTION
**Pull request by SemyonSinchenko**
Related to: https://github.com/apache/incubator-graphar/issues/586

Docs: https://docusaurus.io/docs/markdown-features/code-blocks#supported-languages

### CODE REVIEW

**Comment by SemyonSinchenko** [comment]
Actually I do understand what does this error in deploy mean... I just added a single line of config according to docs

**Comment by SemyonSinchenko** [comment]
@acezen May you please take a look on the error?

**Comment by acezen** [comment]
> @acezen May you please take a look on the error?

Let me see.

**Comment by acezen** [comment]
> @acezen May you please take a look on the error?

Try to replace with
https://github.com/facebook/docusaurus/issues/5013#issuecomment-864385671

the java must be place before scala.

It works in my environment and I don't know why...

**Comment by SemyonSinchenko** [comment]
@acezen It looks like a kind of magic but it works :magic_wand:

**Review by acezen — APPROVED** [review]
LGTM

**Pull request merged**
